groups:
  - name: imaging
    rules:
    - record: imaging:is_sequence_running
      expr: sum without(item) (nina_status{category!~".*Instruction Set.*",item=~".*Container.*"})>0
    - record: imaging:was_sequence_running
      expr: avg_over_time(imaging:is_sequence_running[30m])
    - record: imaging:is_exposing
      expr: nina_status{category!~".*Instruction Set.*",item="TakeExposure"}
    - record: imaging:is_focusing
      expr: nina_status{category!~".*Instruction Set.*",item="RunAutofocus"}
    - record: imaging:was_exposing
      expr: max without(time,gain,filter,offset,binning) (clamp(rate(nina_exposure_total[30m])>0,1,1))>0
    - record: imaging:wait:altitude
      expr: sum without(item) (nina_status{category!~".*Instruction Set.*",item=~"WaitFor.*Altitude"})>0
    - record: imaging:input:message
      expr: nina_status{category!~".*Instruction Set.*",category="Utility",item=~"MessageBox.*"}>0
    - record: imaging:input:rotate
      expr: nina_status{category!~".*Instruction Set.*",category="Telescope",item=~".*Rotate"}>0
    - record: imaging:input:polar_alignment
      expr: nina_status{category!~".*Instruction Set.*",category="Polar Alignment",item="PolarAlignment"}>0
    - record: imaging:input:filter
      expr: nina_status{category!~".*Instruction Set.*",category="Filter Wheel",item="SwitchFilter"}>0
    - record: imaging:error:plate_solve
      expr: max by(host,instance) (rate(nina_error_total{module=~"ASTAP.*"}[5m]))>0

    - alert: ASTAPSolverFailed
      expr: computer:is_connected AND on(host)
            rate(nina_error_total{module=~"ASTAPSolver.*"}[5m])>0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: ASTAP is not able to solve images on host "{{ .Labels.Host }}", check mount limits and tracking.

    - alert: ImagingCrashed
      expr: imaging:is_sequence_running>0 AND on(host)
            imaging:wait:altitude==0 AND on(host)
            rate(nina_total[5m])==0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Imaging has stopped on host "{{ .Labels.Host }}", possibly the process has crashed.

    - alert: ImagingHighErrorRate
      expr: imaging:is_sequence_running>0 AND on(instance,host)
            sum by(instance,host) (rate(nina_error_total{code!="settle"}[10m]))>0
      for: 5m
      labels:
        severity: warning
      annotations:
        message: |
          High rate of errors in imaging software.

    - alert: NinaSideOfPierMissing
      expr: rate(nina_error_total{module="Telescope",type="SideOfPier"}[1m])>0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: |
          NINA is unable to get SideOfPier property from telescope.  Usual fix is full power cycle the rig.

    - alert: ImagingUserInputWarning
      expr: imaging:is_sequence_running>0 AND on(host)
            imaging:input:message>0 
            # These are noise, contributing to alert fatigue.
            # Filter changes are automated now.  Device issues will trigger.
            # I have a message before PA.  I am at the scope.
            # And rotation is done right after PA.  I am at the scope.
            # OR on(host)
            #imaging:input:rotate>0 OR on(host)
            #imaging:input:polar_alignment>0 OR on(host)
            #imaging:input:filter>0
      for: 2m
      labels:
        severity: warning
      annotations:
        message: "Imaging software waiting for user input.  Item: {{ .Labels.Item }}"

    - alert: ImagingUserInputCritical
      expr: imaging:is_sequence_running>0 AND on(host)
            imaging:wait:altitude==0 AND on(host)
            imaging:input:message>0 OR on(host)
            imaging:input:rotate>0 OR on(host)
            imaging:input:filter>0 
      for: 5m
      labels:
        severity: critical
      annotations:
        message: "Imaging software waiting for user input.  Item: {{ .Labels.Item }}"

    - alert: ImagingPolarAlignmentInputCritical
      expr: imaging:input:polar_alignment>0
      for: 15m
      labels:
        severity: critical
      annotations:
        message: "Imaging software waiting for user input.  Item: {{ .Labels.Item }}"

    - alert: GeneralPlateSolveFailed
      expr: device:telescope:is_connected>0 AND on(host)
            imaging:error:plate_solve>0 AND on(host)
            absent(nina_status{category!~".*Instruction Set.*",item="MeridianFlip"}>0) AND on(host)
            absent(nina_status{category!~".*Instruction Set.*",item=~"Center.*"}>0)
      for: 0m
      labels:
        severity: warning
      annotations:
        message: |
          Plate solve has failed recently on host "{{ .Labels.Host }}".

    - alert: CenterPlateSolveFailed
      expr: device:telescope:is_connected>0 AND on(host)
            imaging:error:plate_solve>0 AND on(host)
            nina_status{category!~".*Instruction Set.*",item=~"Center.*"}>0
      for: 15m
      labels:
        severity: critical
      annotations:
        message: |
          Plate solve failed while centering on host "{{ .Labels.Host }}".
          If you see this retries to account for clouds have failed.
          Fix this to get proper centering.

    - alert: MeridianFlipPlateSolveFailed
      expr: device:telescope:is_connected>0 AND on(host)
            imaging:error:plate_solve>0 AND on(host)
            nina_status{category!~".*Instruction Set.*",item="MeridianFlip"}>0
      for: 15m
      labels:
        severity: critical
      annotations:
        message: |
          Plate solve failed after meridian flip on host "{{ .Labels.Host }}".
          If you see this retries to account for clouds have failed.
          Fix this to get proper centering.

    - alert: AutofocusNotRun2h
      expr: imaging:is_sequence_running>0 AND on(host) 
            device:telescope:is_connected>0 AND on(host) 
            nina_status{category!~".*Instruction Set.*",item="RunAutofocus"} == 0 AND on(job)
            condition:is_night>0
      for: 120m
      labels:
        severity: critical
      annotations:
        message: |
          Autofocus has not run in the last 2 hours.  Sequences are setup to run AF every 1.5 hours.
          Cancel sequence, reconnect focuser, run AF manually, start sequence.

    - alert: PoorAutofocus
      expr: device:telescope:is_connected>0 AND on(host)
            avg without(type) (nina_autofocus_rsquares{type!~".*trend|Hyperbolic"})<0.7 AND on()
            condition:is_night > 0
      for: 10m
      labels:
        severity: warning
      annotations:
        message: |
          Autofocus is bad, R^2 average is less than 0.7.
          This should mean AF will use previous settings and image quality may be impacated.

    - alert: FocusDegraded
      expr: nina_detect{type="HFR"} * on(host) 
            (1-nina_status{category!~".*Instruction Set.*",item="RunAutofocus"}) - on(host) 
            avg_over_time(nina_detect{type="HFR"}[1h]) > 1
      for: 15m
      labels:
        severity: warning
      annotations: 
        message: |
          Focus has degraded for a while.  It will eventually correct with AF but ideally should be fixed now.
          NOTE this is not a critial warning because it is expected AF will trigger eventually to correct the problem.

    - alert: FocuserTemperatureLow
      expr: (device:telescope:is_connected > 0 and on (host) alpaca_focuser_temperature < -50 and on () condition:is_night) > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        message: Focuser is reporting temperature is very low.  Just need to disconnect focuser, reconnect in NINA, and verify temperature.

    - alert: FailedToAutoFocus
      expr: device:telescope:is_connected>0 AND on(host)
            rate(nina_error_total{module="Focuser",type="RunAutofocus"}[15m]) > 0 AND on()
            condition:is_night > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        message: "Focuser failed to autofocus.  Reverted to previous focus position.  Likely indicator of obstruction: clouds, tree, house."

    - alert: FailedToSaveImage
      expr: rate(nina_error_total{module="Camera",type="TakeExposure"}[15m]) > 0
            # don't limit to night, could be taking daytime images.
            # don't limit to connected to telescope, could be taking calibration images.
      for: 1m
      labels:
        severity: critical
      annotations:
        message: Unable to save images.  Stop sequence and try to save snapshot.  Might need to reconnect cameras.

    - alert: UncooledImaging
      expr: imaging:was_exposing * on(host)            
            nina_status{category!~".*Instruction Set.*",item=~".*(TargetSchedulerContainer|DeepSkyObjectContainer)"} * on(host)
            device:camera:temperature{camera!~".*(MC-S|Mini|Canon|Nikon|Sony).*"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        message: Taking image but camera sensor is warm.  Did cooling get skipped?

    - alert: UnguidedImaging
      expr: (nina_status{category!~".*Instruction Set.*",item=~".*(TargetSchedulerContainer|DeepSkyObjectContainer)"} - on(host) 
              max by(host) (nina_status{category!~".*Instruction Set.*",category="Telescope",item=~"Center.*"}) - on(host)
              nina_status{category!~".*Instruction Set.*",item="MeridianFlip"}
            )
            * on(host) 
            (guiding:status:is_guiding == bool 0) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Taking image of DSO but not guiding.  Guiding crashed or was missed in sequence.

    - alert: UnguidedImaging
      expr: (nina_status{category!~".*Instruction Set.*",item=~".*(TargetSchedulerContainer|DeepSkyObjectContainer)"} - on(host) 
              max by(host) (nina_status{category!~".*Instruction Set.*",category="Telescope",item=~"Center.*"}))
            * on() 
            absent(guiding:status:is_guiding) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Taking image of DSO but not guiding.  PHD2 may not be running (absense of metrics).

    - alert: GuidingWithoutImaging
      expr: guiding:status:is_guiding > 0 AND on() absent(imaging:is_exposing)
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Guiding but not taking images.  Possibly NINA not running?

    - alert: GuidingWithoutImaging
      expr: guiding:status:is_guiding > on(host) (imaging:is_exposing + on(host) imaging:is_focusing)
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Guiding but not taking images.  Possibly NINA froze?

    - alert: WaitForAltitude
      expr: nina_status{category!~".*Instruction Set.*",item="WaitForAltitude"} * 
            on(job) group_left condition:is_night > 0
      for: 10m
      labels:
        severity: critical
      annotations:
        message: Waiting for target too long.  Probably misconfigured sequence conditions.

    - alert: ImagingStuck
      expr: ((1 - max by(host) (nina_status{category!~".*Instruction Set.*",category=~"(Focuser|Telescope)",item=~"(RunAutofocus|.*Center.*|.*Slew.*|MeridianFlip)"})) * on(host)
              nina_status{category!~".*Instruction Set.*",item!="TakeExposure",item=~".*Exposure"}) > on(host) nina_status{category!~".*Instruction Set.*",item="TakeExposure"} 
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Imaging is stuck somehow, probably need to restart NINA.

    - alert: CameraStuck
      expr: device:telescope:is_connected * on(host) group_right 
            rate(nina_error_total{type=~"Capture.*"}[5m]) > 0
      labels:
        severity: critical
      annotations:
        message: Errors capturing images.  Likely unable to download images.  Restart camera.

    - alert: CouldBeImaging
      expr: (
              device:telescope:is_connected * on(host) max without(item) (nina_status{category!~".*Instruction Set.*",item=~".*Container"}) == bool 0 > 0
            ) AND on()
            (
              condition:is_night * on(latitude,longitude) 
              sgn(max without(source,site) (weather_clouds{when="now"}) < 90) * on(latitude,longitude) 
              sgn((timeOfDay_begin_day - time()) / 60 / 60>1.0)
            )
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Scope is connected, at least 1 hour of night is left, it is not overcast, but no sequence is running.

    - alert: TargetSchedulerStuck
      expr: (
              device:telescope:is_connected * on(host) 
              nina_status{item=~".*TargetAreaContainer"} * on(host)
              nina_status{item="TakeExposure",category="Scheduler"}
            ) == bool 0 > 0
            AND on()
            (
              condition:is_night * on(latitude,longitude) 
              sgn(max without(source,site) (weather_clouds{when="now"}) < 90) * on(latitude,longitude) 
              sgn((timeOfDay_begin_day - time()) / 60 / 60>1.0)
            )
      for: 15m
      labels:
        severity: critical
      annotations:
        message: Target Scheduler plugin is stuck or waiting (no targets).

    - alert: ExcessiveWait
      expr: device:telescope:is_connected * on(host)
            max by(host) (nina_status{category!="Camera",category!~".*Instruction Set.*",item=~"Wait.*"}) * on(host)
            max without(item) (nina_status{item=~"DeepSky.*Container"})
      for: 10m
      labels:
        severity: critical
      annotations:
        message: Waiting for a long time, sequence is stuck somehow.