groups:
  - name: computer
    rules:
    - record: computer:is_connected
      expr: clamp(sum without(core,mode) (rate(windows_cpu_time_total[1m])>0),1,1) OR on(host) (clamp(sum without(core,mode) (rate(windows_cpu_time_total[12h]))-10,0,0))
    - record: computer:was_connected
      expr: clamp(sum without(core,mode) (rate(windows_cpu_time_total[30m])>0),1,1) OR on(host) (clamp(sum without(core,mode) (rate(windows_cpu_time_total[12h]))-10,0,0))

    - alert: ComputerHighTemperature
      expr: computer:is_connected * on(instance)
            windows_thermalzone_temperature_celsius / on(instance)
            windows_thermalzone_percent_passive_limit > 0.9
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Computer "{{ .Labels.Instance }}" temperature is above 90% threshold.

    - alert: ComputerHighUtilization
      expr: computer:is_connected * on(instance)
            avg without (core) (irate(windows_cpu_time_total{mode="idle"}[1m])) < 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        message: |
          Computer "{{ .Labels.Instance }}" utilization is above 90% threshold.
          This can impact power consumption and eventually temperature.
          Can be caused by a rogue process like virus scanning.

    - alert: ComputerOffline
      expr: computer:was_connected > 0 and on(host) computer:is_connected == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: |
          Computer "{{ .Labels.Instance }}" is offline.
          If the computer should be running, it has crashed.  Go restart it.


