groups:
  - name: nina:meridian_flip
    rules:
    - record: nina:meridian_flip:in_progress
      expr: nina_status{category!~".*Instruction Set.*",item="MeridianFlip"}>0 #used to use telescope tracking, but it is disabled when slewing and resets pending alert timers

  - name: nina:alerts
    rules:
    - alert: TelescopeMeridianFlipSlow
      expr: nina:meridian_flip:in_progress>0
      for: 15m
      labels:
        severity: critical
      annotations:
        message: Meridian flip is taking a long time.  Probably unable to plate solve or guiding is stuck.

    - alert: GuidingWithoutTelescope
      expr: guiding:status:is_guiding > on(host) device:telescope:is_connected
      for: 1m
      labels:
        severity: critical
      annotations:
        message: |
          Guiding is enabled but no scope is connected.

    - alert: ExcessiveAutoFocus
      expr: max by(host,camera) (avg_over_time(nina_status{category!~".*Instruction Set.*",item="RunAutofocus"}[1h]) * on(host,camera)
            group_left avg_over_time(nina_status{item="NINA.Sequencer.Container.TargetAreaContainer"}[1h]) * on(host)
            rate(alpaca_focuser_temperature[15m])) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        message: |
          Autofocus is taking more than 10% of imaging time.  Possibly temperature probe is mis-reporting temperature changes.

